declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FeAvatar: typeof import('../packages/core/src')['Avatar']
    FeAvatarGroup: typeof import('../packages/core/src')['AvatarGroup']
    FeBackTop: typeof import('../packages/core/src')['BackTop']
    FeBackdrop: typeof import('../packages/core/src')['Backdrop']
    FeBadge: typeof import('../packages/core/src')['Badge']
    FeBadgeAnchor: typeof import('../packages/core/src')['BadgeAnchor']
    FeBreadcrumbs: typeof import('../packages/core/src')['Breadcrumbs']
    FeBreadcrumbsItem: typeof import('../packages/core/src')['BreadcrumbsItem']
    FeButton: typeof import('../packages/core/src')['Button']
    FeButtonGroup: typeof import('../packages/core/src')['ButtonGroup']
    FeCapacity: typeof import('../packages/core/src')['Capacity']
    FeCard: typeof import('../packages/core/src')['Card']
    FeCheckbox: typeof import('../packages/core/src')['Checkbox']
    FeCheckboxGroup: typeof import('../packages/core/src')['CheckboxGroup']
    FeCode: typeof import('../packages/core/src')['Code']
    FeCollapse: typeof import('../packages/core/src')['Collapse']
    FeCollapseGroup: typeof import('../packages/core/src')['CollapseGroup']
    FeDot: typeof import('../packages/core/src')['Dot']
    FeDrawer: typeof import('../packages/core/src')['Drawer']
    FeForm: typeof import('../packages/core/src')['Form']
    FeFormItem: typeof import('../packages/core/src')['FormItem']
    FeGrid: typeof import('../packages/core/src')['Grid']
    FeGridGroup: typeof import('../packages/core/src')['GridGroup']
    FeImage: typeof import('../packages/core/src')['Image']
    FeImageBrowser: typeof import('../packages/core/src')['ImageBrowser']
    FeInput: typeof import('../packages/core/src')['Input']
    FeInputNumber: typeof import('../packages/core/src')['InputNumber']
    FeLink: typeof import('../packages/core/src')['Link']
    FeLoading: typeof import('../packages/core/src')['Loading']
    FeModal: typeof import('../packages/core/src')['Modal']
    FePagination: typeof import('../packages/core/src')['Pagination']
    FePopover: typeof import('../packages/core/src')['Popover']
    FeProgress: typeof import('../packages/core/src')['Progress']
    FeThemeProvider: typeof import('../packages/core/src')['ThemeProvider']
    FeRadio: typeof import('../packages/core/src')['Radio']
    FeRadioGroup: typeof import('../packages/core/src')['RadioGroup']
    FeRating: typeof import('../packages/core/src')['Rating']
    FeSelect: typeof import('../packages/core/src')['Select']
    FeSelectOption: typeof import('../packages/core/src')['SelectOption']
    FeSkeleton: typeof import('../packages/core/src')['Skeleton']
    FeSkeletonItem: typeof import('../packages/core/src')['SkeletonItem']
    FeSlider: typeof import('../packages/core/src')['Slider']
    FeSnippet: typeof import('../packages/core/src')['Snippet']
    FeSpacer: typeof import('../packages/core/src')['Spacer']
    FeSwitch: typeof import('../packages/core/src')['Switch']
    FeTab: typeof import('../packages/core/src')['Tab']
    FeTabs: typeof import('../packages/core/src')['Tabs']
    FeTag: typeof import('../packages/core/src')['Tag']
    FeTextarea: typeof import('../packages/core/src')['Textarea']
    FeThemes: typeof import('../packages/core/src')['Themes']
    FeToast: typeof import('../packages/core/src')['Toast']
    FeTooltip: typeof import('../packages/core/src')['Tooltip']
    FeUpload: typeof import('../packages/core/src')['Upload']
    FeUser: typeof import('../packages/core/src')['User']
  }
}

export {}
